const MODULES={
 matter:{s:'Chemistry',u:'Unit 01 — Matter & Measurement',t:'Matter & Measurement',q:'How can observable properties help us classify matter?',intro:'Change a sample\'s particle spacing and composition, then watch how its state and classification respond.',a:['Temperature',0,100,35,'°C'],b:['Composition',0,100,20,'% solute'],mode:'matter',pred:['More ordered','More energetic','No change']},
 stoichiometry:{s:'Chemistry',u:'Unit 01 — Matter & Measurement',t:'Stoichiometry',q:'What happens when one reactant runs out first?',intro:'Change the amounts of two reactants and watch particles pair into products. The leftovers reveal the limiting reactant.',a:['Reactant A',1,20,8,' particles'],b:['Reactant B',1,20,12,' particles'],mode:'stoich',pred:['A limits','B limits','Neither']},
 atomic:{s:'Chemistry',u:'Unit 02 — Atomic World',t:'Atomic Structure',q:'What changes when you change protons, neutrons or electrons?',intro:'Build an atom and see its nucleus, electron cloud, charge and identity change together.',a:['Protons',1,12,6,''],b:['Electrons',0,12,6,''],mode:'atom',pred:['Charge changes','Element changes','Nothing changes']},
 configuration:{s:'Chemistry',u:'Unit 02 — Atomic World',t:'Electronic Configuration',q:'Where do electrons go as atomic number increases?',intro:'Add electrons and watch them occupy shells from lower to higher energy.',a:['Electrons',1,20,10,''],b:['Excitation',0,100,0,'%'],mode:'electron',pred:['Inner shells first','Outer shells first','Randomly']},
 periodic:{s:'Chemistry',u:'Unit 02 — Atomic World',t:'Periodic Trends',q:'Why do properties change across the periodic table?',intro:'Move across a simplified period and group to visualize atomic radius and electronegativity trends.',a:['Across period',1,8,4,''],b:['Down group',1,5,2,''],mode:'periodic',pred:['Radius shrinks across','Radius grows across','No trend']},
 covalent:{s:'Chemistry',u:'Unit 03 — Chemical Bonding',t:'Covalent Bonding',q:'What changes when atoms share instead of transfer electrons?',intro:'Move two atoms together and adjust shared electron pairs to see bond order and attraction change.',a:['Atom distance',20,100,65,'%'],b:['Shared pairs',1,3,1,''],mode:'covalent',pred:['Electrons share','Electrons transfer','Atoms ignore each other']},
 geometry:{s:'Chemistry',u:'Unit 03 — Chemical Bonding',t:'Molecular Geometry',q:'How do electron regions decide molecular shape?',intro:'Change bonding and lone-pair regions and watch the geometry reorganize to reduce repulsion.',a:['Bond regions',2,6,4,''],b:['Lone pairs',0,2,0,''],mode:'geometry',pred:['Spread apart','Cluster together','Stay linear']},
 states:{s:'Chemistry',u:'Unit 04 — States, Energy & Gases',t:'States of Matter',q:'What does heating actually do to particles?',intro:'Add thermal energy and watch particle speed, spacing and order change from solid-like to gas-like behavior.',a:['Temperature',0,100,25,'%'],b:['Pressure',10,100,50,'%'],mode:'states',pred:['Particles move faster','Particles stop','Mass disappears']},
 gaslaws:{s:'Chemistry',u:'Unit 04 — States, Energy & Gases',t:'Gas Laws',q:'What happens to pressure when you squeeze a gas?',intro:'Move the virtual piston and change temperature while particle collisions update in real time.',a:['Volume',25,100,70,'%'],b:['Temperature',200,600,300,' K'],mode:'gas',pred:['Pressure rises','Pressure falls','Pressure stays same']},
 thermo:{s:'Chemistry',u:'Unit 04 — States, Energy & Gases',t:'Thermochemistry',q:'Where does energy go during a chemical change?',intro:'Change reaction energy and watch an energy profile move between reactants, activation barrier and products.',a:['Activation energy',10,90,55,' kJ'],b:['Reaction ΔH',-80,80,-30,' kJ'],mode:'thermo',pred:['Products lower','Products higher','Always equal']},
 reaction:{s:'Chemistry',u:'Unit 05 — Reactions & Equilibrium',t:'Chemical Reactions',q:'How do particles become new substances?',intro:'Increase collision energy and watch reactant particles rearrange into products only when conditions are sufficient.',a:['Collision energy',0,100,55,'%'],b:['Orientation quality',0,100,65,'%'],mode:'reaction',pred:['More effective collisions','No effect','Fewer products']},
 rates:{s:'Chemistry',u:'Unit 05 — Reactions & Equilibrium',t:'Reaction Rates',q:'Why do some reactions happen faster?',intro:'Change temperature and concentration to alter collision frequency and reaction speed.',a:['Temperature',10,100,45,'%'],b:['Concentration',10,100,50,'%'],mode:'rates',pred:['Rate increases','Rate decreases','No change']},
 equilibrium:{s:'Chemistry',u:'Unit 05 — Reactions & Equilibrium',t:'Chemical Equilibrium',q:'Does equilibrium mean the reaction stops?',intro:'Watch A ⇌ B continue in both directions while the overall amounts settle into a dynamic balance.',a:['Forward tendency',10,100,55,'%'],b:['Reverse tendency',10,100,45,'%'],mode:'equilibrium',pred:['Both directions continue','Everything stops','Only forward continues']},
 acidbase:{s:'Chemistry',u:'Unit 05 — Reactions & Equilibrium',t:'Acids & Bases',q:'What does a pH value represent at the particle level?',intro:'Change hydrogen-ion concentration and watch the pH indicator and particle balance respond.',a:['Acid strength',0,100,65,'%'],b:['Base added',0,100,20,'%'],mode:'acidbase',pred:['pH falls with more acid','pH rises with more acid','No change']},
 electrochem:{s:'Chemistry',u:'Unit 06 — Electrochemistry & Organic',t:'Electrochemistry',q:'How can a chemical reaction push electrons through a wire?',intro:'Change the redox driving force and resistance to see electron flow and ion migration in a simple cell.',a:['Driving force',10,100,70,'%'],b:['Resistance',10,100,40,'%'],mode:'battery',pred:['Electrons flow faster','Electrons stop','Ions vanish']},
 organic:{s:'Chemistry',u:'Unit 06 — Electrochemistry & Organic',t:'Organic Chemistry',q:'How does carbon build so many different molecules?',intro:'Change chain length and branching to watch a carbon skeleton reorganize.',a:['Carbon count',2,10,5,''],b:['Branching',0,100,30,'%'],mode:'organic',pred:['More structures become possible','Only one structure','Carbon cannot branch']},
 life:{s:'Biology',u:'Unit 01 — Foundations of Life',t:'Characteristics of Life',q:'What makes a system behave like something alive?',intro:'Change energy input and environmental stress, then watch a simple organism model maintain or lose stable function.',a:['Energy available',0,100,70,'%'],b:['Environmental stress',0,100,25,'%'],mode:'life',pred:['Stable function','Immediate failure','No response']},
 biomolecules:{s:'Biology',u:'Unit 01 — Foundations of Life',t:'Biomolecules',q:'How does molecular structure relate to biological function?',intro:'Change chain length and folding tendency to see a simple biomolecule shift from linear to compact forms.',a:['Chain length',3,20,10,' units'],b:['Folding tendency',0,100,55,'%'],mode:'biomolecule',pred:['Shape changes','Function never depends on shape','No structure forms']},
 cell:{s:'Biology',u:'Unit 01 — Foundations of Life',t:'Cell Structure',q:'How do organelles cooperate inside a cell?',intro:'Change cell activity and energy demand to watch organelles respond as one coordinated system.',a:['Cell activity',0,100,55,'%'],b:['Energy demand',0,100,60,'%'],mode:'cell',pred:['Mitochondria become busier','Nucleus disappears','Membrane stops']},
 membrane:{s:'Biology',u:'Unit 02 — Cell Processes',t:'Cell Membrane',q:'Why can some substances cross a membrane while others cannot?',intro:'Change molecule size and membrane permeability to watch selective transport happen.',a:['Molecule size',1,100,35,'%'],b:['Membrane permeability',0,100,65,'%'],mode:'membrane',pred:['Small molecules cross easier','Large always cross','Nothing crosses']},
 diffusion:{s:'Biology',u:'Unit 02 — Cell Processes',t:'Diffusion',q:'Why do particles spread out without being pushed?',intro:'Create a concentration difference and watch random motion produce a net movement down the gradient.',a:['Left concentration',10,100,85,'%'],b:['Temperature',10,100,50,'%'],mode:'diffusion',pred:['Particles spread out','Particles cluster more','Movement stops']},
 respiration:{s:'Biology',u:'Unit 02 — Cell Processes',t:'Cellular Respiration',q:'How does a cell turn fuel into usable ATP?',intro:'Change glucose and oxygen supply to see ATP production respond and identify the limiting input.',a:['Glucose',0,100,70,'%'],b:['Oxygen',0,100,55,'%'],mode:'respiration',pred:['Lowest input limits ATP','Only glucose matters','ATP is fixed']},
 cycle:{s:'Biology',u:'Unit 03 — Cell Reproduction',t:'Cell Cycle',q:'How does a cell prepare safely for division?',intro:'Move through growth and DNA-copying conditions to see whether the model cell reaches division.',a:['Growth readiness',0,100,70,'%'],b:['DNA copy quality',0,100,80,'%'],mode:'cycle',pred:['Checkpoints matter','Division always happens','DNA is irrelevant']},
 mitosis:{s:'Biology',u:'Unit 03 — Cell Reproduction',t:'Mitosis',q:'How does one nucleus become two genetically matched nuclei?',intro:'Move through mitosis and watch chromosomes condense, align, separate and reform nuclei.',a:['Mitosis stage',0,100,0,'%'],b:['Spindle strength',20,100,75,'%'],mode:'mitosis',pred:['Chromatids separate','DNA disappears','One chromosome remains']},
 meiosis:{s:'Biology',u:'Unit 03 — Cell Reproduction',t:'Meiosis',q:'How does meiosis create variation?',intro:'Advance through two divisions and change crossing-over to see four genetically varied cells emerge.',a:['Division progress',0,100,0,'%'],b:['Crossing over',0,100,45,'%'],mode:'meiosis',pred:['Four varied cells','Two identical cells','One cell']},
 mendel:{s:'Biology',u:'Unit 04 — Genetics',t:'Mendelian Genetics',q:'How can parental alleles predict offspring ratios?',intro:'Change allele dominance and sample size, then watch predicted and simulated offspring distributions compare.',a:['Sample size',20,300,100,' offspring'],b:['Dominant allele chance',0,100,50,'%'],mode:'punnett',pred:['Ratios emerge over many offspring','Every child is identical','Probability guarantees one child']},
 dna:{s:'Biology',u:'Unit 04 — Genetics',t:'DNA Structure',q:'How can a molecule store information?',intro:'Twist and unzip a simplified DNA model to see paired bases and complementary structure.',a:['Unzip amount',0,100,20,'%'],b:['Twist',0,100,60,'%'],mode:'dna',pred:['Bases pair specifically','Any base pairs','Strands are unrelated']},
 replication:{s:'Biology',u:'Unit 04 — Genetics',t:'DNA Replication',q:'How can one DNA molecule become two?',intro:'Advance replication and change copying accuracy to watch complementary strands form.',a:['Replication progress',0,100,0,'%'],b:['Copy accuracy',70,100,98,'%'],mode:'replication',pred:['Each old strand guides a new one','DNA copies without template','Bases vanish']},
 protein:{s:'Biology',u:'Unit 04 — Genetics',t:'Protein Synthesis',q:'How does genetic information become a protein?',intro:'Move translation forward and alter available amino acids to watch a polypeptide chain grow.',a:['Translation progress',0,100,0,'%'],b:['Amino acids available',10,100,80,'%'],mode:'protein',pred:['Chain grows at ribosome','DNA leaves nucleus and becomes protein','Nothing changes']},
 circulation:{s:'Biology',u:'Unit 05 — Human Systems',t:'Circulation',q:'How does one red blood cell travel through the heart and body?',intro:'Change heart rate and vessel resistance while a blood cell travels through a simplified circulation loop.',a:['Heart rate',40,160,75,' bpm'],b:['Vessel resistance',10,100,35,'%'],mode:'heart',pred:['Flow changes','Blood stops permanently','Valves disappear']},
 respiratory:{s:'Biology',u:'Unit 05 — Human Systems',t:'Respiratory System',q:'How do oxygen and carbon dioxide cross between air and blood?',intro:'Change breathing depth and oxygen gradient to watch gas exchange across an alveolar membrane.',a:['Breathing depth',10,100,60,'%'],b:['Oxygen gradient',10,100,70,'%'],mode:'lungs',pred:['Steeper gradient increases exchange','Gradient has no effect','Oxygen moves randomly overall']},
 nervous:{s:'Biology',u:'Unit 05 — Human Systems',t:'Nervous System',q:'How does a signal travel quickly across a neuron?',intro:'Change stimulus strength and myelination to watch an action-potential pulse propagate.',a:['Stimulus strength',0,100,70,'%'],b:['Myelination',0,100,65,'%'],mode:'neuron',pred:['Myelin speeds conduction','Myelin stops all signals','Stimulus never matters']},
 digestion:{s:'Biology',u:'Unit 05 — Human Systems',t:'Digestion',q:'How does food become molecules small enough to absorb?',intro:'Change enzyme activity and food particle size to watch breakdown and absorption speed change.',a:['Enzyme activity',0,100,65,'%'],b:['Food particle size',10,100,55,'%'],mode:'digestion',pred:['More enzyme speeds breakdown','Larger pieces always digest faster','Absorption happens before breakdown']},
 photosynthesis:{s:'Biology',u:'Unit 06 — Plants, Evolution & Ecology',t:'Photosynthesis',q:'What limits the rate of photosynthesis?',intro:'Change light and carbon dioxide to see which factor limits sugar production.',a:['Light intensity',0,100,60,'%'],b:['CO₂ availability',0,100,45,'%'],mode:'photosynthesis',pred:['Lowest resource limits rate','Only light matters','Rate never changes']},
 planttransport:{s:'Biology',u:'Unit 06 — Plants, Evolution & Ecology',t:'Plant Transport',q:'How does water move from roots to leaves?',intro:'Change transpiration and soil water to watch the xylem water column move upward.',a:['Transpiration',0,100,65,'%'],b:['Soil water',0,100,70,'%'],mode:'xylem',pred:['More transpiration pulls more water','Water moves only downward','Leaves do not affect flow']},
 evolution:{s:'Biology',u:'Unit 06 — Plants, Evolution & Ecology',t:'Evolution',q:'How can selection change a population over generations?',intro:'Change environmental selection and mutation to watch trait frequencies shift across generations.',a:['Selection pressure',0,100,60,'%'],b:['Mutation',0,100,15,'%'],mode:'evolution',pred:['Trait frequencies shift','Every organism changes instantly','Populations never change']},
 ecology:{s:'Biology',u:'Unit 06 — Plants, Evolution & Ecology',t:'Ecology',q:'Why can changing one population affect many others?',intro:'Change producer abundance and predator pressure to watch a small food web rebalance.',a:['Producer abundance',10,100,70,'%'],b:['Predator pressure',10,100,45,'%'],mode:'foodweb',pred:['Effects spread through web','Only one species changes','Food webs are static']}
};

const params=new URLSearchParams(location.search), id=params.get('id'), M=MODULES[id];
if(!M){document.body.innerHTML='<main class="module-shell"><h1>Module not found</h1><a href="../index.html">Back to Study Notebook</a></main>';throw new Error('Unknown module '+id)}
const $=s=>document.querySelector(s);document.title=M.t+' — Study Notebook';
$('#crumb').textContent=M.s+' / '+M.u;$('#subjectChip').textContent=M.s.toUpperCase()+' • INTERACTIVE LAB';$('#title').textContent=M.t;$('#intro').textContent=M.intro;$('#question').textContent=M.q;
$('#aLabel').textContent=M.a[0];$('#bLabel').textContent=M.b[0];const A=$('#a'),B=$('#b');[A.min,A.max,A.value]=[M.a[1],M.a[2],M.a[3]];[B.min,B.max,B.value]=[M.b[1],M.b[2],M.b[3]];$('#back').href='../index.html#'+(M.s==='Chemistry'?'chemistry-path':'biology-path');$('#back').textContent='← Back to '+M.s;
const pred=$('#predictions');M.pred.forEach((p,i)=>{const b=document.createElement('button');b.textContent=p;b.type='button';b.onclick=()=>{pred.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#predictionFeedback').textContent=i===0?'Good prediction. Now test it in the lab.':'Keep that prediction—use the simulation to test it.'};pred.appendChild(b)});
let running=true,t=0,raf;const c=$('#sim'),ctx=c.getContext('2d');
function fit(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(600,Math.floor(r.width*d));c.height=Math.max(360,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);return {w:r.width,h:r.height}}window.addEventListener('resize',fit);
function col(name){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()||'#333'}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function line(x1,y1,x2,y2,stroke=col('--ink'),lw=2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}
function text(s,x,y,size=13){ctx.fillStyle=col('--muted');ctx.font=size+'px Inter,system-ui';ctx.fillText(s,x,y)}
function particles(n,w,h,speed=1,region){for(let i=0;i<n;i++){const seed=i*91.73;let x=(Math.sin(seed+t*.0008*speed+i)*.5+.5)*(region?.w||w-60)+(region?.x||30);let y=(Math.cos(seed*1.7+t*.001*speed+i)*.5+.5)*(region?.h||h-90)+(region?.y||35);circle(x,y,4,col('--accent'))}}
function render(){const {w,h}=fit(),a=+A.value,b=+B.value;ctx.clearRect(0,0,w,h);ctx.lineWidth=1.5;const ink=col('--ink'),accent=col('--accent'),muted=col('--muted');
 switch(M.mode){
 case 'matter':{const energy=a/100;particles(12+Math.round(b/8),w,h,.5+energy*3);text(energy<.33?'ordered / solid-like':energy<.68?'flowing / liquid-like':'rapid / gas-like',22,28,15);break}
 case 'stoich':{const na=Math.round(a),nb=Math.round(b),prod=Math.min(na,Math.floor(nb/2));for(let i=0;i<na;i++)circle(40+(i%10)*18,50+Math.floor(i/10)*24,6,accent);for(let i=0;i<nb;i++)circle(40+(i%10)*18,130+Math.floor(i/10)*24,5,ink);line(w*.45,40,w*.45,h-40,muted);for(let i=0;i<prod;i++){circle(w*.58+(i%6)*35,65+Math.floor(i/6)*42,7,accent);circle(w*.58+10+(i%6)*35,65+Math.floor(i/6)*42,5,ink);circle(w*.58+10+(i%6)*35,76+Math.floor(i/6)*42,5,ink)}text('A + 2B → AB₂',w*.55,30,16);break}
 case 'atom':case 'electron':{const p=M.mode==='atom'?Math.round(a):Math.max(1,Math.round(a)),e=M.mode==='atom'?Math.round(b):Math.round(a),cx=w/2,cy=h/2;circle(cx,cy,22,ink);text(M.mode==='atom'?p+'p⁺':e+'e⁻',cx-12,cy+5,12);const shells=[55,90,125];shells.forEach(r=>circle(cx,cy,r,null,muted));for(let i=0;i<e;i++){let sh=i<2?0:i<10?1:2,cap=sh===0?2:8,idx=sh===0?i:sh===1?i-2:i-10,ang=(idx/cap)*Math.PI*2+t*.0004*(M.mode==='electron'?(1+b/100):1);circle(cx+Math.cos(ang)*shells[sh],cy+Math.sin(ang)*shells[sh],6,accent)}break}
 case 'periodic':{const radius=65+b*7-a*5;circle(w*.35,h*.52,Math.max(20,radius),null,accent);text('atomic radius',w*.22,35,15);ctx.fillStyle=accent;ctx.fillRect(w*.58,h*.63,Math.min(w*.3,a*24),14);text('electronegativity →',w*.58,h*.58,14);break}
 case 'covalent':case 'geometry':{const cx=w/2,cy=h/2;if(M.mode==='covalent'){const d=150-a;circle(cx-d/2,cy,25,null,ink);circle(cx+d/2,cy,25,null,ink);for(let i=0;i<b;i++){circle(cx-6,cy-10+i*10,5,accent);circle(cx+6,cy-10+i*10,5,accent)}text('shared electron region',cx-65,cy+65,14)}else{const n=Math.round(a),lp=Math.round(b);circle(cx,cy,18,ink);for(let i=0;i<n;i++){const ang=(i/n)*Math.PI*2;line(cx,cy,cx+Math.cos(ang)*110,cy+Math.sin(ang)*110,ink,2);circle(cx+Math.cos(ang)*110,cy+Math.sin(ang)*110,18,null,accent)}for(let i=0;i<lp;i++)circle(cx+Math.cos(i*Math.PI)*48,cy+Math.sin(i*Math.PI)*48,8,accent);text(n+' bond regions • '+lp+' lone pairs',25,30,14)}break}
 case 'states':case 'gas':{const vol=M.mode==='gas'?a/100:.8, boxW=w*(.35+.55*vol),x=(w-boxW)/2;ctx.strokeStyle=ink;ctx.strokeRect(x,45,boxW,h-90);const temp=M.mode==='gas'?b:a;particles(26,x+boxW,h-90,.8+temp/120,{x:x+5,y:50,w:boxW-10,h:h-100});if(M.mode==='gas'){line(x+boxW,35,x+boxW,h-35,accent,6);text('piston',x+boxW-20,28,12)}break}
 case 'thermo':{const base=h*.68,act=a/100*h*.38,dh=b/160*h*.38;ctx.beginPath();ctx.moveTo(40,base);ctx.bezierCurveTo(w*.3,base,w*.35,base-act,w*.5,base-act);ctx.bezierCurveTo(w*.65,base-act,w*.7,base+dh,w-40,base+dh);ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.stroke();text('reactants',40,base+25);text('products',w-120,base+dh+25);break}
 case 'reaction':case 'rates':case 'equilibrium':{const speed=M.mode==='rates'?(.5+a/50+b/60):1.1, n=28;for(let i=0;i<n;i++){let x=(Math.sin(i*3.1+t*.0005*speed+i)*.5+.5)*(w-80)+40,y=(Math.cos(i*4.4+t*.0007*speed+i)*.5+.5)*(h-100)+50;circle(x,y,6,i%3===0?accent:ink)}if(M.mode==='equilibrium'){line(w/2,35,w/2,h-35,muted);text('A ⇌ B keeps moving',w/2-62,28,15)}break}
 case 'acidbase':{const ph=Math.max(0,Math.min(14,7+(b-a)*.07));ctx.fillStyle=accent;ctx.fillRect(50,h*.52,(w-100)*(ph/14),22);ctx.strokeStyle=ink;ctx.strokeRect(50,h*.52,w-100,22);text('0 acidic',50,h*.52+48);text('7 neutral',w/2-30,h*.52+48);text('14 basic',w-115,h*.52+48);text('pH '+ph.toFixed(1),w/2-25,h*.35,24);break}
 case 'battery':{const speed=Math.max(.2,a/(b+15));line(80,h*.35,w-80,h*.35,ink,4);line(80,h*.65,w-80,h*.65,ink,4);ctx.strokeRect(60,h*.32,35,h*.36);ctx.strokeRect(w-95,h*.32,35,h*.36);for(let i=0;i<7;i++){let x=90+((i*80+t*.05*speed)%(w-180));circle(x,h*.35,5,accent)}particles(12,w,h,.7,{x:100,y:h*.42,w:w-200,h:h*.18});break}
 case 'organic':{const n=Math.round(a),branch=b/100,cx=70,cy=h/2;for(let i=0;i<n;i++){let x=cx+i*Math.min(60,(w-140)/(n-1)),y=cy+(i%2?18:-18);if(i){let px=cx+(i-1)*Math.min(60,(w-140)/(n-1)),py=cy+((i-1)%2?18:-18);line(px,py,x,y,ink,3)}circle(x,y,10,accent);if(branch>.45&&i>1&&i<n-1&&i%2===0){line(x,y,x,y-55,ink,2);circle(x,y-55,8,null,accent)}}break}
 case 'life':case 'cell':{const health=Math.max(0,Math.min(1,a/100-b/150+.35)),cx=w/2,cy=h/2;ctx.save();ctx.translate(cx,cy);ctx.scale(.85+health*.2,.85+health*.2);ctx.beginPath();ctx.ellipse(0,0,150,95,0,0,Math.PI*2);ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.stroke();circle(-35,0,30,null,ink);for(let i=0;i<8;i++)circle(55+Math.sin(i)*40,-20+Math.cos(i*2)*45,8,i%2?accent:ink);ctx.restore();text(health>.65?'stable system':health>.35?'under stress':'function failing',30,35,17);break}
 case 'biomolecule':{const n=Math.round(a),fold=b/100;ctx.beginPath();for(let i=0;i<n;i++){let x=40+i*(w-80)/(n-1),y=h/2+Math.sin(i*1.3+t*.001)*(15+fold*60);i?ctx.lineTo(x,y):ctx.moveTo(x,y);circle(x,y,5,accent)}ctx.strokeStyle=ink;ctx.stroke();break}
 case 'membrane':case 'diffusion':{line(w/2,30,w/2,h-30,ink,4);const cross=M.mode==='membrane'?Math.max(0,b-a):b;for(let i=0;i<28;i++){let side=i<18?0:1,span=w/2-50,x=(Math.sin(i*4+t*.0004*cross)*.5+.5)*span+25+(side?w/2:0),y=(Math.cos(i*2.7+t*.0007*b)*.5+.5)*(h-80)+40;circle(x,y,5,accent)}text(M.mode==='membrane'?'selective crossing':'net movement: high → low',30,28,15);break}
 case 'respiration':case 'photosynthesis':{const rate=Math.min(a,b);ctx.fillStyle=accent;ctx.fillRect(55,h-70,(w-110)*rate/100,24);ctx.strokeStyle=ink;ctx.strokeRect(55,h-70,w-110,24);const label=M.mode==='respiration'?'ATP production':'sugar production';text(label+': '+Math.round(rate)+'%',55,h-88,16);particles(10+Math.round(rate/8),w,h,.6);break}
 case 'cycle':{const ready=Math.min(a,b);circle(w/2,h/2,110,null,muted);ctx.beginPath();ctx.arc(w/2,h/2,110,-Math.PI/2,-Math.PI/2+Math.PI*2*ready/100);ctx.strokeStyle=accent;ctx.lineWidth=10;ctx.stroke();text(ready>70?'checkpoint passed':'checkpoint waiting',w/2-65,h/2+5,16);break}
 case 'mitosis':case 'meiosis':{const prog=a/100,cx=w/2,cy=h/2;if(M.mode==='mitosis'){ctx.beginPath();ctx.ellipse(cx,cy,150,95,0,0,Math.PI*2);ctx.strokeStyle=accent;ctx.stroke();const sep=Math.max(0,(prog-.45))*170;for(let i=0;i<4;i++){let yy=cy-45+i*30;line(cx-sep,yy-10,cx-sep,yy+10,ink,3);line(cx+sep,yy-10,cx+sep,yy+10,ink,3)}if(prog>.75)line(cx,cy-90,cx,cy+90,muted,2)}else{const cells=prog<.5?2:4;for(let i=0;i<cells;i++){const x=cx+(i%2?70:-70),y=cy+(i>1?55:-35);circle(x,y,35,null,accent);line(x-10,y-12,x+10,y+12,ink,2);line(x+10,y-12,x-10,y+12,ink,2)}}break}
 case 'punnett':{const p=b/100,n=Math.round(a),dom=Math.round(n*(1-(1-p)*(1-p)));ctx.fillStyle=accent;ctx.fillRect(70,h*.45,(w-140)*dom/n,26);ctx.strokeStyle=ink;ctx.strokeRect(70,h*.45,w-140,26);text('dominant phenotype ~ '+Math.round(dom/n*100)+'%',70,h*.45-18,16);break}
 case 'dna':case 'replication':{const open=a/100,cx=w/2;for(let i=0;i<24;i++){const y=35+i*(h-70)/23,sep=18+open*70*Math.sin(Math.PI*i/23),wave=Math.sin(i*.9+t*.001)*18;circle(cx-sep+wave,y,4,accent);circle(cx+sep-wave,y,4,ink);if(M.mode==='dna'||i/23<open)line(cx-sep+wave,y,cx+sep-wave,y,muted,1)}break}
 case 'protein':{const prog=a/100,avail=b/100;line(40,h*.45,w*.45,h*.45,accent,4);ctx.strokeRect(w*.43,h*.35,70,70);const count=Math.round(16*prog*avail);for(let i=0;i<count;i++){const x=w*.57+i*18,y=h*.45+Math.sin(i*.8)*25;circle(x,y,6,i%2?accent:ink);if(i)line(x-18,h*.45+Math.sin((i-1)*.8)*25,x,y,muted,2)}break}
 case 'heart':{const rate=a/75,speed=Math.max(.2,rate*(1-b/130));ctx.beginPath();ctx.moveTo(w*.5,h*.7);ctx.bezierCurveTo(w*.28,h*.5,w*.32,h*.22,w*.5,h*.4);ctx.bezierCurveTo(w*.68,h*.22,w*.72,h*.5,w*.5,h*.7);ctx.strokeStyle=accent;ctx.lineWidth=4;ctx.stroke();for(let i=0;i<8;i++){let ang=(t*.0005*speed+i/8)*Math.PI*2,x=w/2+Math.cos(ang)*w*.33,y=h/2+Math.sin(ang)*h*.28;circle(x,y,5,accent)}break}
 case 'lungs':{const depth=a/100,grad=b/100;ctx.beginPath();ctx.ellipse(w*.38,h*.55,70,110*depth,0,0,Math.PI*2);ctx.ellipse(w*.62,h*.55,70,110*depth,0,0,Math.PI*2);ctx.strokeStyle=accent;ctx.stroke();for(let i=0;i<14;i++){let x=w*.28+(i%7)*w*.065,y=h*.32+Math.floor(i/7)*h*.34+Math.sin(t*.001+i)*12*grad;circle(x,y,5,i%2?accent:ink)}break}
 case 'neuron':{const threshold=a>35,speed=.4+b/70;circle(70,h/2,35,null,ink);line(105,h/2,w-80,h/2,ink,5);for(let i=0;i<7;i++)line(140+i*70,h/2-18,140+i*70,h/2+18,accent,6);if(threshold){let x=110+((t*.08*speed)%(w-190));circle(x,h/2,9,accent)}text(threshold?'action potential firing':'below threshold',35,35,16);break}
 case 'digestion':{const rate=(a/100)*(1-b/130);const count=Math.max(2,Math.round(22*(1-rate)));for(let i=0;i<count;i++)circle(60+(i%8)*45,70+Math.floor(i/8)*60,4+b/20,accent);text('breakdown rate '+Math.round(rate*100)+'%',40,h-35,16);break}
 case 'xylem':{const flow=Math.min(a,b)/100;line(w/2,h-40,w/2,60,ink,16);for(let i=0;i<8;i++){let y=h-50-((i*55+t*.05*flow)%(h-110));circle(w/2,y,6,accent)}ctx.beginPath();ctx.ellipse(w/2-70,80,65,25,-.3,0,Math.PI*2);ctx.ellipse(w/2+70,80,65,25,.3,0,Math.PI*2);ctx.strokeStyle=accent;ctx.stroke();break}
 case 'evolution':{const sel=a/100,mut=b/100;for(let i=0;i<45;i++){const fav=(i/45)<sel;let x=40+(i%15)*(w-80)/14,y=60+Math.floor(i/15)*85,c=fav?accent:ink;circle(x,y,5+mut*4,c)}text('selection shifts trait frequency across generations',35,h-30,15);break}
 case 'foodweb':{const prod=a/100,pred=b/100,nodes=[[w*.18,h*.65],[w*.4,h*.38],[w*.42,h*.75],[w*.68,h*.52],[w*.83,h*.28]];[[0,1],[0,2],[1,3],[2,3],[3,4]].forEach(e=>line(...nodes[e[0]],...nodes[e[1]],muted,2));nodes.forEach((p,i)=>circle(p[0],p[1],18*(i===0?prod+.4:i===4?pred+.4:.8),i===0?accent:null,ink));break}
 }
 const m1=M.mode==='gas'?(b/(a||1)).toFixed(2):M.mode==='photosynthesis'||M.mode==='respiration'?Math.min(a,b)+'%':Math.round(a)+M.a[4];const m2=Math.round(b)+M.b[4];$('#m1').textContent=m1;$('#m2').textContent=m2;$('#m3').textContent=running?'Live':'Paused';$('#aVal').textContent=Math.round(a)+M.a[4];$('#bVal').textContent=Math.round(b)+M.b[4];$('#observation').textContent=observation(M.mode,a,b);if(running)t+=16;raf=requestAnimationFrame(render)}
function observation(mode,a,b){const map={gas:a<50?'Smaller volume means more frequent wall collisions, so pressure rises.':'More space means collisions with the walls are less frequent.',states:a>70?'High thermal energy produces fast, widely spaced particle motion.':a<30?'Low thermal energy keeps particles slower and more ordered.':'Particles can flow past one another.',diffusion:'Random motion continues, but the concentration difference creates a net movement from high to low concentration.',membrane:a<b?'Permeability is high relative to molecule size, so more particles cross.':'The membrane blocks more of these particles.',photosynthesis:Math.min(a,b)===a?'Light is currently the limiting factor.':'CO₂ is currently the limiting factor.',respiration:Math.min(a,b)===a?'Glucose supply currently limits ATP production.':'Oxygen supply currently limits ATP production.',equilibrium:'Both forward and reverse events continue. Equilibrium is dynamic, not stopped.',acidbase:a>b?'Acid influence dominates, so the model shifts toward lower pH.':'Base addition is neutralizing the acid influence.',neuron:a>35?'The stimulus exceeds threshold, so a pulse propagates along the axon.':'The stimulus is below threshold, so no full action potential fires.'};return map[mode]||'Change one variable at a time and watch which part of the system responds most strongly.'}
A.oninput=B.oninput=()=>{};$('#toggle').onclick=()=>{running=!running;$('#toggle').textContent=running?'Pause':'Play'};$('#reset').onclick=()=>{A.value=M.a[3];B.value=M.b[3];running=true;$('#toggle').textContent='Pause'};render();
